css_assignment/urls.py
from django.urls import path
from . import views
app_name='css_asg'

urlpatterns=[
    path('master_home/', views.getmasterhome,name="Master"),
    path('home_home/', views.gethomehome,name="Home"),
    path('courses_home/', views.getcourseshome,name="Courses"),
    path('contact_home/', views.getcontacthome,name="Contact"),
]

customers/urls.py
from django.urls import path
from . import views
app_name='cust'

urlpatterns=[
    path('customers_home/', views.getcustomershome,name="Customers"),
    path('abcd_home/', views.getabcdhome,name="ABCD"),
    path('masterrr_home/', views.getmasterrrhome,name="Masterrr"),
    path('change_password/', views.getchangepassword,name="ChangePassword"),
    path('my_profile/', views.getmyprofile,name="MyProfile"),
    path('settings_home/', views.getmysettingshome,name="Settings"),
    path('xyz_home/', views.getxyzhome,name="XYZ"),
    path('css1_home/', views.getcss1home,name="CSS1"),
    path('css2_home/', views.getcss2home,name="CSS2"),
    path('css3_home/', views.getcss3home,name="CSS3"),
    path('css4_home/', views.getcss4home,name="CSS4"),
    path('machinetest1_home/', views.getmachinetest1home,name="MachineTest1"),
    path('css5_home/', views.getcss5home,name="CSS5"),
    path('machinetest2_home/', views.getmachinetest2home,name="MachineTest2"),
    path('cssgridlayout_home/', views.getcssgridlayouthome,name="cssgridlayout"),
    path('cssgridlayout2_home/', views.getcssgridlayout2home,name="cssgridlayout2"),
    path('bootstrap_home/', views.getbootstraphome,name="bootstrap"),
    path('bootstrapgridsystem_home/', views.getbootstrapgridsystemhome,name="bootstrapgridsystem"),
    path('bootstrap1_home/', views.getbootstrap1home,name="bootstrap1"),
    path('bootstrap2_home/', views.getbootstrap2home,name="bootstrap2"),
    path('bootstrap3_home/', views.getbootstrap3home,name="bootstrap3"),
    path('javascript_home/', views.getjavascripthome,name="javascript"),
    path('javascript2_home/', views.getjavascript2home,name="javascript2"),
    path('javascript3_home/', views.getjavascript3home,name="javascript3"),
    path('javascript4_home/', views.getjavascript4home,name="javascript4"),
    path('javascript5_home/', views.getjavascript5home,name="javascript5"),
    path('formvalidation_home/', views.getformvalidationhome,name="formvalidation"),
    path('javascript6_home/', views.getjavascript6home,name="javascript6"),
    path('jquery_home/', views.getjqueryhome,name="jquery"),
    path('jquery2_home/', views.getjquery2home,name="jquery2"),
    path('formvalidation2_home/', views.getformvalidation2home,name="formvalidation2"),
    path('jquery3_home/', views.getjquery3home,name="jquery3"),
    path('jquery4_home/', views.getjquery4home,name="jquery4"),
    path('animations_home/', views.getanimationshome,name="animations"),
    path('json_home/', views.getjsonhome,name="json"),
    path('synchronous_home/', views.getsynchronoushome,name="synchronous"),
    path('asyncawait_home/', views.getasyncawaithome,name="asyncawait"),
]

libraian/urls.py
from django.urls import path
from . import views 
app_name='lib'

urlpatterns=[
    path('libraians_home/', views.getlibrarianshome,name="Library"),
    path('book_collection/', views.getbooks,name="Books")
]

library_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('libraian/', include('libraian.urls')),
    path('customers/', include('customers.urls')),
    path('css_assignment/', include('css_assignment.urls')),
]

css_assignment/models.py
from django.db import models

# Create your models here.

css_assignment/views.py
from django.shortcuts import render

# Create your views here.
def getmasterhome(request):
    return render(request,'master.html')

def gethomehome(request):
    return render(request,'home.html')

def getcourseshome(request):
    return render(request,'courses.html')

def getcontacthome(request):
    return render(request,'contact.html')

customers/views.py
from django.shortcuts import render

# Create your views here.
def getcustomershome(request):
    return render(request,'customers.html')

def getabcdhome(request):
    return render(request,'abcd.html')

def getmasterrrhome(request):
    return render(request, 'masterrr.html')

def getchangepassword(request):
    return render(request, 'changepassword.html')

def getmyprofile(request):
    return render(request, 'myprofile.html')

def getmysettingshome(request):
    return render(request, 'settings.html')

def getxyzhome(request):
    return render(request, 'xyz.html')

def getcss1home(request):
    return render(request, 'css1.html')

def getcss2home(request):
    return render(request, 'css2.html')

def getcss3home(request):
    return render(request, 'css3.html')

def getcss4home(request):
    return render(request, 'css4.html')

def getmachinetest1home(request):
    return render(request, 'machinetest1.html')

def getcss5home(request):
    return render(request, 'css5.html')

def getmachinetest2home(request):
    return render(request, 'machinetest2.html')

def getcssgridlayouthome(request):
    return render(request, 'cssgridlayout.html')

def getcssgridlayout2home(request):
    return render(request, 'cssgridlayout2.html')

def getbootstraphome(request):
    return render(request, 'bootstrap.html')

def getbootstrapgridsystemhome(request):
    return render(request, 'bootstrapgridsystem.html')

def getbootstrap1home(request):
    return render(request, 'bootstrap1.html')

def getbootstrap2home(request):
    return render(request, 'bootstrap2.html')

def getbootstrap3home(request):
    return render(request, 'bootstrap3.html')

def getjavascripthome(request):
    return render(request, 'javascript.html')

def getjavascript2home(request):
    return render(request, 'javascript2.html')

def getjavascript3home(request):
    return render(request, 'javascript3.html')

def getjavascript4home(request):
    return render(request, 'javascript4.html')

def getjavascript5home(request):
    return render(request, 'javascript5.html')

def getformvalidationhome(request):
    return render(request, 'formvalidation.html')
    
def getjavascript6home(request):
    return render(request, 'javascript6.html')

def getjqueryhome(request):
    return render(request, 'jquery.html')

def getjquery2home(request):
    return render(request, 'jquery2.html')

def getformvalidation2home(request):
    return render(request, 'formvalidation2.html')

def getjquery3home(request):
    return render(request, 'jquery3.html')

def getjquery4home(request):
    return render(request, 'jquery4.html')

def getanimationshome(request):
    return render(request, 'animations.html')

def getjsonhome(request):
    return render(request, 'json.html')

def getsynchronoushome(request):
    return render(request, 'synchronous.html')

def getasyncawaithome(request):
    return render(request, 'asyncawait.html')

libraian/views.py
from django.shortcuts import render

# Create your views here.

def getlibrarianshome(request):
    return render(request,'librarians.html')

def getbooks(request):
    return render(request,'books.html')

css_assignment/templates/contact.html
{% extends "master.html" %}
{% load static %}


{% block header %}
<link rel="stylesheet" href="{% static 'styles/course.css' %}">
{% endblock %}


{% block content %}


<br>
<table border="1" cellpadding="3" align="center">

    <tr>
        <th colspan="2"><h3>Contact Us</h3></th>
    </tr>
    <tr>
        <td>Nmae</td>
        <td><input type="text" name="" id=""></td>
    </tr>

    <tr>
        <td>Gender</td>
        <td> <input type="radio" name="" id="">Male
            <input type="radio" name="" id="">Female
        </td>
    </tr>
   
    <tr>
        <td>Date of Birth</td>
        <td> <input type="date" name="" id=""></td>
    </tr>

    <tr>
        <td>Mobile</td>
        <td><input type="text"></td>
    </tr>

    <tr>
        <td>Email</td>
        <td><input type="text"></td>
    </tr>

    <tr>
        <td>Address</td>
        <td><textarea name="" id="" cols="30" rows="5"></textarea></td>
    </tr>

    <tr>
        <td colspan="2" align="right"><br><a href="#" class="link_button">Submit</a><br><br></td>
    </tr>

</table>
{% endblock %}

css_assignment/templates/courses.html
{% extends "master.html" %}
{% load static %}


{% block header %}
<link rel="stylesheet" href="{% static 'styles/course.css' %}">
{% endblock %}


{% block content %}

    
<div id="paradiv">
    <h2>Explore Our internship programme</h2>
    <p id="para">baabtra.com offers you courses and training programs that will enable you to master programming in depth. Enroll and start learning with the experts in the industry
        We offer PHP Training with Laravel Framework, Python Training with Django Framework, Angular Training and Node.js Training.</p>
</div>
<br><br><br>

<div class="grid-container">

    <div class="grid-item">
        <img src="{% static 'images/python.png' %}" class="course_imge" alt="">
        <h3>Python Full Stack Development</h3>
        <p>
            Python is one of the most popular programming languages in the world nowadays. If you look at the future and world like to work in the feild of Big Data, Cloud computing, Machine Learning, Data Science, Robotics, Artificial Intelligence etc, you should consider learning this language. Python rogrammers are getting more demand in the IT industry.
        </p>
    </div>

    <div class="grid-item">
        <img src="{% static 'images/php.jpg' %}" class="course_imge" alt="">
        <h3>PHP Full Stack Development</h3>
        <p>
            PHP is the one of the most common programming languages used by SME companies for software development and hence there will be enough job opportunities for PHP developers all the time. Candidates also find this as an easy language to master. For those who have knoledge in framework like Laravel, getting a software developer job would be an easy task.
        </p>
    </div>

    <div class="grid-item">
        <img src="{% static 'images/angular.jpg' %}" class="course_imge" alt="">
        <h3>Angular - Front End Development</h3>
        <p>
            This program would be a great choice for those who would like to work as a frontend developer in a software company. Baabtra offers internship programs in Front end development which makes a candidate capable of handling client side application with Angular. Angular is a typescript based web application framework supported by Google.
        </p>
    </div>

</div>
<br><br><br>

{% endblock %}

css_assignment/templates/home.html
{% extends 'master.html' %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'styles/home.css' %}">
{% endblock %}

{% block content %}

   
    <div class="banner">
        <img src="{% static 'images/banner.jpg' %}" width="100%" alt="">
    </div>

    <div class="content_head">
        <h1 align="center" id="heading">GETTING A SOFTWARE JOB IS SO EASY WITH OUR INTERNSHIP PROGRAM</h1>
    <p>Learn programming from the most trusted software training company in Calicut with highest placement record. Enroll for software courses and internship programs in Python, Java, PHP, Angular or Node.js to start your career.</p>
    </div>

    <div class="grid-container">

        <div class="grid-item">
            <h3 align="center">Our Office</h3>
            <img src="{% static 'images/baabtra_offic.jpg' %}" alt="" width="250">
        </div>

        <div class="grid-item">
            <h3 align="center">Best Python Training In Calicut</h3>
            <p>Python is one of the hot programming languages nowadays.
                Many freshers are learning this software development technology and are getting placed as Python Deveploper in Software Companies. Baabtra has the highest number of candidates got trained in Python in the last year.
                We train you to develop a web application using Python with Django framework and MySql database. Python trainng course for freshers to make them good programmers through quality trainng in Python & Django Framework in Calicut.</p>
        </div>

        <div class="grid-item">
            <h3 align="center">Life @ baabtra</h3>
            <iframe width="420" height="315" src="https://www.youtube.com/embed/LIGnK7711fA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>

    </div>

{% endblock %}

css_assignment/templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home page</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    {% block header %}

    {% endblock %}
    <style type="text/css">
        p{
            padding: 10px;
        }
    </style>
</head>
<body>
    
<div class="container">
    <div class="logo_div">
        <img src="{% static 'images/logo.png' %}" alt="">
        <img style="text-align: right; float: right; margin-top:20px;" alt="">
        <img src="{% static 'images/login.png' %}" height="180">
        <img src="{% static 'images/register.png' %}" height="180" style=>
    </div>

</div>

<div class="topnav">
<a class="active" href="{% url 'css_asg:Home' %}">Home</a>
<a href="{% url 'css_asg:Courses' %}">Courses</a>
<a href="{% url 'css_asg:Contact' %}">Contact Us</a>

</div>

<div class="content">
    {% block content %}

    {% endblock %}
</div>

<div class="footer">
    <div class="grid-container">
        <div class="grid-item" style="padding: 5px; padding-left: 20px;">
            baabtra <br>
            Mentoring Partner
        </div>
        <div class="grid-item" style="padding: 5px;">
            <b>Email:</b> infor@baabtra.com<br>
            <b>Phone:</b> +91-8592 058 444<br>
        </div>
        <div class="grid-item" style="padding: 5px;">
            <b>Address</b> <br>
            5<sup>th</sup> Floor, CaFIT Square, <br>Hi lite Bsuiness Parl, Kozhikode
        </div>
    </div>
</div>

</body>
</html>

customers/templates/abcd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>dfsd</h1>
    <a href="{% url 'lib:Books' %}">Click here</a>
</body>
</html>

customers/templates/animations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>

<style>
    #box-container {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        grid-template-rows: repeat(3, 1fr);
        width: 150px;
        height: 150px;
    }

    .box{
        background-color: red;
        transition: all o.5s;
    }
</style>
</head>
<body>
    
<button id="rotateBtn">Rotate Box</button>
<div id="box-container">
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
    <div class="box"></div>
</div>

<script>

$('#rotateBtn').click(function(){
    $('#box-container').animate({
        width: '300px',
        height: '300px',
        gap: '5px'
    }, 1000);
    $('.box').animate({
        width: '100px',
        height: '100px',
        margin: '1%'
    }, 1000);
    $('.box').css({
        transform: 'rotate(90deg)',
        transition: 'all 1s'
    });
})

</script>
</body>
</html>

customers/templates/bootstrap1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <style>

    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <a class="navbar-brand" href="#">Navbar</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                  
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                            Dropdown
                          </a>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                          </div>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link disabled">Disabled</a>
                        </li>
                      </ul>
                      <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                      </form>
                    </div>
                  </nav>
            </div>

            <div class="col-md-12">
              <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img src="{% static 'images/download2.jpg/' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="{% static 'images/download3.jpg/' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="{% static 'images/download4.png/' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="{% static 'images/download5.png/' %}" class="d-block w-100" alt="...">
                    </div>
                  </div>
                 <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-target="#carouselExampleControls" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </button>
                </div>
              </div>

              <br><br>
    <hr>
    <div class="col-md-1"></div>
    
    <div class="col-md-3">
      <div class="card" style="width: 18rem;">
        <img src="{% static 'images/download3.jpg/' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Shigatsu wa Kimi no Uso</h5>
          <p class="card-text">Shigatsu wa Kimi no Uso is a Japanese romantic drama manga series that was written and illustrated by Naoshi Arakawa.</p>
          <a href="https://en.wikipedia.org/wiki/Your_Lie_in_April" class="btn btn-primary">Go to Wikipedia Page</a>
        </div>
      </div>
    </div>

    <div class="col-md-3" style="margin-left: 10px;">
      <div class="card" style="width: 18rem;">
        <img src="{% static 'images/download4.png/' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">JoJo no Kimiyou na Bouken</h5>
          <p class="card-text">An adaptation of the Japanese manga series of the same name by Hirohiko Araki, the series focuses on the mysterious adventures of the Joestar family across generations.</p>
          <a href="https://en.wikipedia.org/wiki/JoJo%27s_Bizarre_Adventure_(TV_series)" class="btn btn-primary">Go to Wikipedia Page</a>
        </div>
    </div>
  </div>

    <div class="col-md-3">
      <div class="card" style="width: 300px;">
        <img src="{% static 'images/download2.jpg/' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Jujutsu Kaisen</h5>
          <p class="card-text">JoJo no Kimyō na Bōken is a Japanese anime television series produced by David Production. An adaptation of the Japanese manga series of the same name by Hirohiko Araki, the series focuses on the mysterious adventures of the Joestar family across generations, from the end of the 19th century to modern times.</p>
          <a href="https://en.wikipedia.org/wiki/JoJo%27s_Bizarre_Adventure_(TV_series)" class="btn btn-primary">Go to Wikipedia Page</a>
        </div>
    </div>
  </div>

    <div class="col-md-1"></div>

        </div>
    </div>

<!-- WITHOUT CONTROLS~ -->

    <!-- <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'images/download2.jpg/' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="{% static 'images/download3.jpg/' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="{% static 'images/download4.png/' %}" class="d-block w-100" alt="...">
        </div>
      </div>
    </div> -->

<!-- WITH CONTROLS~ -->

    
    

    

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    
</body>
</html>

customers/templates/customers.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2 style="color: teal;"><center>Heloo</center></h2>
    <img src="{% static 'images/download.jfif' %}" alt="">
</body>
</html>

customers/templates/formvalidation2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>


</head>
<body>
    
<h1 style="font-size: 200%;"><center>Registeration</center></h1>

<form action="" method="get" name="form1">

    
</form>

</body>
</html>

customers/templates/javascript.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="{% static 'javascript/script1.js' %}"></script>
</head>
<body>

    
 <button onclick="alert('hello')">Click</button> 

 <button onclick="message()">click</button>

 <button onclick="addnumbers(10,20)">Add</button>

<script>
    alert('Welcome to Baabtra')
    function message(){
        document.write("<h1>Hello</h1>")
    }
    // console.log(addnumbers(1,22))
    d=addnumbers(1,22)
    console.log(d)
    function addnumbers(a,b){
        c=a+b;
        return c
        // console.log(c)
    }
    myname=prompt('please enter your name')
    console.log(myname)

    confirm('Are you sure you want to exit?')

    num1=parseInt(prompt('Enter the first number'));
    num2=parseInt(prompt('Enter the second number'));
    result=num1+num2;
    console.log(result)

    function example(){
        myname1='daniya';
    }
    example()
    console.log(myname1)

    console.log(4%2);
    
    n1=5;
    console.log(++n1);
    n1++;

    console.log(2**4);

    x=10;
    x=x+7;
    console.log(x);

    x!=10;
    console.log(x>10);

    x1=10;
    console.log(x1=='10');
    console.log(x1==='10');

    console.log(x>1 && x<100);

    
    

    
</script>
</body>
</html>

customers/templates/javascript2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<script>

// y=parseInt(prompt('Enter number'));
//     if (y>0){
//       console.log('the number is positive')  
//     }
//     else if (y==0){
//         console.log ('the number is zero')
//     }
//     else {
//         console.log('the number is negative')
//     }

z=parseInt(prompt('Enter marks'));
    if (z>=90 && z<=100){
        console.log('A1')
    }
    else if (z>=80 && z<90){
        console.log('A2')
    }
    else if (z>=70 && z<80){
        console.log('B1')
    }
    else if (z>=60 && z<70){
        console.log('B2')
    }
    else if (z>=50 && z<60){
        console.log('C1')
    }
    else if (z>=40 && z<50){
        console.log('C2')
    }
    else if (z>=30 && z<40){
        console.log('D')
    }
    else if (z>=0 && z<30){
        console.log('F')
    }
    else {
        console.log('Invalid Input')
    }

v1=parseInt(prompt('Enter your age'));
v2=prompt('Enter your nationality');
    if (v2=='indian'){
        if (v1>=18){
            console.log('you are eligible for voting')
        }
        else {
            console.log('you have not reached 18 years')
        }
    }
    else {
        console.log('you are not indian')
    }

a=parseInt(prompt('Enter a number between 1 to 7'));
    switch(a){
        case 1:
            console.log('Monday')
            break;
        case 2:
            console.log('Tuesday')
            break;
        case 3:
            console.log('Wednesday')
            break;
        case 4:
            conosle.log('Thursday')
            break;
        case 5:
            console.log('Friday')
            break;
        case 6:
            console.log('Saturday')
            break;
        case 7:
            console.log('Sunday')
            break;
        default :
            console.log('Invalid Input')
    }

</script>

</body>
</html>

customers/templates/masterrr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div style="height: 650px; width: 400px; border: 1px solid; float: left;">
    <ul>
        <li><a href="{% url 'cust:MyProfile' %}">My Profile</a></li>
        <li> <a href="{% url 'cust:ChangePassword' %}">Change Password</a></li>
        <li> <a href="{% url 'cust:Settings' %}">Settings</a></li>
    </ul>
    </div>
    <div style="height: 650px; width: 900px; float: left; border: 1px solid; margin-left: 20px;">
    {% block content %}
    {% endblock %}

</div>
</body>
</html>

customers/templates/settings.html
{% extends 'master.html' %}
{% block content %}
    <h1>Settings</h1>
    {% endblock %}

customers/templates/xyz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="color: seagreen;">HELLO</h1>
</body>
</html>

libraian/templates/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <h1><center>Book Collections</center></h1> 
</body>
</html>